module.exports = [
  {
    _id: '1',
    name: 'Classic Methi Khakhra',
    image: '/images/methi.jpg',
    shortDescription: 'Crunchy flatbread made with wholesome millets and fenugreek.',
    description: 'Crispy, savory khakhra made from millet flour, balanced with fenugreek and light spices for guilt-free snacking.',
    price: 189,
    originalPrice: 229,
    flavor: 'Fenugreek & Cumin',
    giValue: '38',
    netWeight: 180,
    countInStock: 14,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Khakhra',
  },
  {
    _id: '2',
    name: 'Curry Leaf Millet Bites',
    image: '/images/curry leaves.jpg',
    shortDescription: 'Aromatic millet crackers with curry leaf and pepper.',
    description: 'Golden, crisp bites layered with curry leaf and subtle spice, perfect for a light, flavorful snack anytime.',
    price: 199,
    originalPrice: 249,
    flavor: 'Curry Leaf & Pepper',
    giValue: '35',
    netWeight: 160,
    countInStock: 10,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Snack',
  },
  {
    _id: '3',
    name: 'Garlic Pepper Millet Crisp',
    image: '/images/garlic.jpg',
    shortDescription: 'Bold garlic crisp made with nutrient-rich grains.',
    description: 'Thin, crunchy crisps with roasted garlic and cracked black pepper, crafted for a savory, wholesome bite.',
    price: 179,
    originalPrice: 209,
    flavor: 'Garlic & Black Pepper',
    giValue: '40',
    netWeight: 170,
    countInStock: 8,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Snack',
  },
  {
    _id: '4',
    name: 'Moringa Seed Energy Thins',
    image: '/images/garlic.jpg',
    shortDescription: 'Light, nutrient-dense seeds baked into a savory crunch.',
    description: 'A nourishing blend of moringa, seeds, and millet flour delivers fiber-rich energy that keeps you going.',
    price: 235,
    originalPrice: 279,
    flavor: 'Moringa & Seed Blend',
    giValue: '32',
    netWeight: 150,
    countInStock: 9,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Energy Bites',
  },
  {
    _id: '5',
    name: 'Coconut Millet Crunch',
    image: '/images/onion.jpg',
    shortDescription: 'A subtly sweet crunch with coconut and millet layers.',
    description: 'Delicately roasted coconut pairs with millet for a crispy snack that satisfies sweet cravings without refined sugar.',
    price: 215,
    originalPrice: 249,
    flavor: 'Coconut & Millet',
    giValue: '39',
    netWeight: 170,
    countInStock: 12,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Sweet',
  },
  {
    _id: '6',
    name: 'Herbal Khakhra Variety Pack',
    image: '/images/hero-khakhra.png',
    shortDescription: 'Mixed herb khakhra pack for everyday wellness.',
    description: 'A collection of three herbal flavors, each crafted to deliver crisp texture and balanced nutrition for daily snacking.',
    price: 269,
    originalPrice: 319,
    flavor: 'Mixed Herbs',
    giValue: '37',
    netWeight: 200,
    countInStock: 7,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Khakhra',
  },
  {
    _id: '7',
    name: 'Garden Spice Millet Crackers',
    image: '/images/methi.jpg',
    shortDescription: 'Savory millet crackers spiced with garden herbs.',
    description: 'Every bite is crisp and aromatic with a peppery garden herb blend that pairs perfectly with tea or dips.',
    price: 199,
    originalPrice: 229,
    flavor: 'Garden Herbs',
    giValue: '36',
    netWeight: 165,
    countInStock: 11,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Snack',
  },
  {
    _id: '8',
    name: 'Spiced Sesame Millet Thins',
    image: '/images/jeera.jpg',
    shortDescription: 'Thin millet crisps with toasted sesame and spice.',
    description: 'Light, crisp thins seasoned with sesame and warm spices for a healthy snack that delivers satisfying texture and taste.',
    price: 189,
    originalPrice: 219,
    flavor: 'Sesame & Spice',
    giValue: '34',
    netWeight: 155,
    countInStock: 16,
    isLowGI: true,
    isGlutenFree: true,
    isVegan: true,
    category: 'Snack',
  },
];
